#!/bin/bash
### ---
### name: 'rustyMetal (test_gapless)'
### outputs:
### - 'rusty_metal_test_gapless.csv'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/61/e68217b78501399c1beb09c0878de7/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/61/e68217b78501399c1beb09c0878de7/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f probcons.fasta
    rm -f muscle.fasta
    rm -f kalign.fasta
    rm -f clustalo.fasta
    rm -f prank.fasta
    rm -f t_coffee.fasta
    rm -f fsa.fasta
    rm -f clustalw.fasta
    rm -f mafft_auto.fasta
    rm -f amap.fasta
    rm -f mafft_linsi.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/bf/01e56d362f6f8c38369c527066c480/test_gapless/probcons.fasta probcons.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/ae/f6563ce32e8e377fb2075e429b3f88/test_gapless/muscle.fasta muscle.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/6a/830fb573a57ede028c1d6a1b93593b/test_gapless/kalign.fasta kalign.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/48/b71221dd726cce3b382b45a48e578d/test_gapless/clustalo.fasta clustalo.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/89/ca13864f1aa991a9c6ab6864e85d36/test_gapless/prank.fasta prank.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/c8/08216fa6c8e194c65ebe5736304a11/test_gapless/t_coffee.fasta t_coffee.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/91/7f7454fc4ea45ead5d0c512c11db93/test_gapless/fsa.fasta fsa.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/9d/65be8f7070fe73cfd5aaa8c0499d48/test_gapless/clustalw.fasta clustalw.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/4a/d17ca549937a36ab38bc3ed0d9ec74/test_gapless/mafft_auto.fasta mafft_auto.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/38/7cbacd3217eaaa1c25dcd1f0ac2eed/test_gapless/amap.fasta amap.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/d0/9bd6afa05d4d4d3758447a35e982af/test_gapless/mafft_linsi.fasta mafft_linsi.fasta
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/61/e68217b78501399c1beb09c0878de7/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
