#!/bin/bash
### ---
### name: 'rustyMetal (test_gapless)'
### outputs:
### - 'rusty_metal_test_gapless.csv'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/ab/9078a1b8835ee16240b31eddf84d14/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/ab/9078a1b8835ee16240b31eddf84d14/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f probcons.fasta
    rm -f muscle.fasta
    rm -f clustalo.fasta
    rm -f kalign.fasta
    rm -f prank.fasta
    rm -f t_coffee.fasta
    rm -f clustalw.fasta
    rm -f fsa.fasta
    rm -f mafft_auto.fasta
    rm -f amap.fasta
    rm -f mafft_linsi.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/89/667e65fd8286a1b18e9f8f48441900/test_gapless/probcons.fasta probcons.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/15/9fba45aa6501ab32a7e7c0430f53a4/test_gapless/muscle.fasta muscle.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/51/2e85fe7f0dde95e5aa8f43f03b2422/test_gapless/clustalo.fasta clustalo.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/e4/7635b207ae5b9689364f207885fae2/test_gapless/kalign.fasta kalign.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/de/c424fd076553ca5d8b40adb6e199a1/test_gapless/prank.fasta prank.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/64/eae1108deaf8a3b021dccd4710592e/test_gapless/t_coffee.fasta t_coffee.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/99/65c3291681622895bae27f3630dff5/test_gapless/clustalw.fasta clustalw.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/0d/bf48aadd87ad1378bb72d23ade0b2e/test_gapless/fsa.fasta fsa.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/ab/74d446685c33ab6f5b2b40f10e71b1/test_gapless/mafft_auto.fasta mafft_auto.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/7e/14be4848d75c9d23140b1c94edebce/test_gapless/amap.fasta amap.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/aa/7054651813e62575704524a6d62d26/test_gapless/mafft_linsi.fasta mafft_linsi.fasta
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/ab/9078a1b8835ee16240b31eddf84d14/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
