#!/bin/bash
### ---
### name: 'rustyMetal (test)'
### outputs:
### - 'rusty_metal_test.csv'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/a5/4a983995bf7142adcfba452b83f92f/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/a5/4a983995bf7142adcfba452b83f92f/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f probcons.fasta
    rm -f kalign.fasta
    rm -f muscle.fasta
    rm -f clustalo.fasta
    rm -f prank.fasta
    rm -f t_coffee.fasta
    rm -f clustalw.fasta
    rm -f fsa.fasta
    rm -f mafft_auto.fasta
    rm -f amap.fasta
    rm -f mafft_linsi.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/05/952715ce53adb66336d67d5ecdb39b/test/probcons.fasta probcons.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/e1/d9c86b073ef3509d11e7c72e917091/test/kalign.fasta kalign.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/86/8912a7f011220ed5c533574f283a86/test/muscle.fasta muscle.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/c4/d1033722ba596a86ee6e7feaecd544/test/clustalo.fasta clustalo.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/7b/3aacbf5e5d247527a44b5c5f025bfc/test/prank.fasta prank.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/7b/df8161f4d95f8d4cd03d2c9c703ff2/test/t_coffee.fasta t_coffee.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/e6/6d99df896f9e1fb5228fbaa6185deb/test/clustalw.fasta clustalw.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/6e/b4edae5ad4dc539412e531028f3355/test/fsa.fasta fsa.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/9d/6b2c4a6ca4e82ba960624c7d446306/test/mafft_auto.fasta mafft_auto.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/aa/2675b69c4b9aa90c40993c8637c986/test/amap.fasta amap.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/c1/935dffd4ec3d37fe1e781bd55d375b/test/mafft_linsi.fasta mafft_linsi.fasta
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/a5/4a983995bf7142adcfba452b83f92f/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
