#!/bin/bash
### ---
### name: 'rustyMetal (test_gapless)'
### outputs:
### - 'test_gapless/rusty_metal.csv'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local s n
    read s n < <(date '+%s %N')
    if [[ $n =~ ^[0-9]+$ ]]; then
        n=$(printf '%09d' "$((10#$n))")
        echo "$((s * 1000 + 10#${n:0:3}))"
    else
        echo "$((s * 1000))"
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  local source=$1
  local target=$2
  mkdir -p $target
  rsync -rRl $source $target
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    local last_err=$?
    local exit_status=${nxf_main_ret:=0}
    [[ ${exit_status} -eq 0 && ${nxf_unstage_ret:=0} -ne 0 ]] && exit_status=${nxf_unstage_ret:=0}
    [[ ${exit_status} -eq 0 && ${last_err} -ne 0 ]] && exit_status=${last_err}
    printf -- $exit_status > /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/fa/dd8682d425f905c82a33a0964734cf/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/fa/dd8682d425f905c82a33a0964734cf/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f probcons.fasta
    rm -f clustalo.fasta
    rm -f muscle.fasta
    rm -f kalign.fasta
    rm -f prank.fasta
    rm -f t_coffee.fasta
    rm -f fsa.fasta
    rm -f clustalw.fasta
    rm -f mafft.fasta
    rm -f amap.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/5e/a480924ac47e8226a39dc59639a22d/test_gapless/probcons.fasta probcons.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/4c/b1160ba888a25dd172db3a3a815f13/test_gapless/clustalo.fasta clustalo.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/93/fa578a93b2a777e607198d1d978cca/test_gapless/muscle.fasta muscle.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/f5/b3d4caf21c428204f27d012d2acf34/test_gapless/kalign.fasta kalign.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/d1/925d7f7cb883b8993541be592e2d36/test_gapless/prank.fasta prank.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/0b/a2aab671587b0a79e0dfe4dc8b5edd/test_gapless/t_coffee.fasta t_coffee.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/33/6e58e02a27669c7b383030ce9721b9/test_gapless/fsa.fasta fsa.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/7f/2c44a0c82ac26687857dc99423e0d9/test_gapless/clustalw.fasta clustalw.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/7f/443e7ff2b4138b26f6af99314b1639/test_gapless/mafft.fasta mafft.fasta
    ln -s /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/4c/db5c111c0232d7796b77ba71d89bbf/test_gapless/amap.fasta amap.fasta
}

nxf_unstage_outputs() {
    true
}

nxf_unstage_controls() {
    true
}

nxf_unstage() {
    if [[ ${nxf_main_ret:=0} == 0 ]]; then
        (set -e -o pipefail; (nxf_unstage_outputs | tee -a .command.out) 3>&1 1>&2 2>&3 | tee -a .command.err)
        nxf_unstage_ret=$?
    fi
    nxf_unstage_controls
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /home/byna/Documents/Code/Project/pipeline/MSA-comparison-pipeline/work/fa/dd8682d425f905c82a33a0964734cf/.command.begin
    set +u
    set -u
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
